### ISSUE TITLE
Mock methods can't consume their parameters

### ISSUE THREAD

**Issue by asomers** [pcsm/simulacrum#53]
`simulacrum_mock::method::TrackedMethod::returning` gets function parameters by reference.  This makes it impossible for the supplied closure to consume the parameters.  This is important for parameters that aren't `Clone` and do something non-trivial on `Drop`.  Here is some example code, using Mockers, that consumes method parameters in the mock method.  The mock method moves its parameters into the global variable `dest`
```rust
#[derive(Debug, Eq, PartialEq)]
pub struct UniquelyOwned(u32);

#[derive_mock]
pub trait A {
    fn foo(&self, x: UniquelyOwned);
}

#[test]
fn consume_parameters() {
    let dest: Arc<RefCell<Option<UniquelyOwned>>> =
        Arc::new(RefCell::new(None));
    let dest2 = dest.clone();
    let scenario = Scenario::new();
    let mock = scenario.create_mock_for::<A>();
    scenario.expect(mock.foo_call(matchers::ANY).and_call(move |x| {
        dest2.replace(Some(x));
    }));

    mock.foo(UniquelyOwned(42));
    assert!(dest.borrow().is_some());
}
```

**Comment by jasongrlicky** [comment]
Hey, thank you for this issue and the pull request! I'm just getting back from vacation, but I should be able to take a look at these this week. 👍
