### ISSUE TITLE
Add crates.io and docs.rs badges to each crate's Readme

### ISSUE THREAD

**Issue by jasongrlicky** [pcsm/simulacrum#7]

**Comment by Atul9** [comment]
@jasongrlicky I would like to work on this

**Comment by jasongrlicky** [comment]
Re-opening, because we should actually add the badges to the README.md in each of the `simulacrum` and `simulacrum_macros` sub-directories.

**Comment by jasongrlicky** [comment]
Fixed in 07d34f07a288ab212c2f9374af2624cf8ccb8f46
